import {check,equal,SIMD_PROBE} from './core.mjs';
let list,points,numeric,copied;
const digest=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const snapshot=async value=>({used:value.arena.used,root:value.root,tail:value.tail,size:value.size,depth:value.depth,digest:await digest(new Uint8Array(value.arena.memory.buffer))});
onmessage=async({data})=>{try{let result;if(data.kind==='attach'){
  copied=data.copy;const {initWorker}=await import('/dist/shared.js');({list,points}=await initWorker(data.data));const mode=new URL(location.href).searchParams.get('mode');numeric=await import('/dist/'+(mode==='scalar'?'numeric-scalar-control.mjs':'numeric.js'));
  const original=WebAssembly.validate;let probes=0;try{WebAssembly.validate=bytes=>{equal(Array.from(bytes),SIMD_PROBE);check(++probes===1);return mode==='scalar'?false:original.call(WebAssembly,bytes);};check(numeric.countInRange(list,0,2)===33);}finally{WebAssembly.validate=original;}check(probes===1);result={ready:true,selection:mode};
}else{check(data.kind==='read');const fullMemoryCheck=copied||!data.concurrentOwnerMayWrite;const visible=value=>({root:value.root,tail:value.tail,size:value.size,depth:value.depth,values:Array.from({length:value.size},(_,i)=>value.get(i))});const before=fullMemoryCheck?[await snapshot(list),await snapshot(points)]:[visible(list),visible(points)],counts=[numeric.countInRange(list,0,2),numeric.countPointsInBox(points,{minX:0,minY:0,maxX:2,maxY:2})];for(const item of [list,points]){let rejected=false;try{item.push(7);}catch{rejected=true;}check(rejected,'Worker attachment must reject writes');}equal(fullMemoryCheck?[await snapshot(list),await snapshot(points)]:[visible(list),visible(points)],before);result={counts,readOnly:true,memoryPreserved:fullMemoryCheck?'whole buffers across isolated read':'visible snapshot across concurrent owner writes'};}
postMessage({id:data.id,result});}catch(error){postMessage({id:data.id,error:String(error),stack:error.stack});}};
