import { escape, codeBlock } from './render.mjs';
import { repository } from './config.mjs';

const arrow = '<span aria-hidden="true">↗</span>';
const logo = '<svg viewBox="0 0 28 28" width="28" height="28" aria-hidden="true"><path d="M3 4h22v5L10 19h15v5H3v-5L18 9H3z" fill="currentColor"/></svg>';
export function shell({ title, description, body, base, route = '', script, version, sha, origin }) {
  const href = path => base + path;
  const canonical = origin ? `<link rel="canonical" href="${escape(origin + href(route))}">` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f8f2"><title>${escape(title)} · zerocopy</title><meta name="description" content="${escape(description)}"><meta property="og:title" content="${escape(title)} · zerocopy"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website">${canonical}<link rel="icon" href="${href('assets/icon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${href('assets/site.css')}"><script type="module" src="${href('assets/main.mjs')}"></script>${script ? `<script type="module" src="${href('assets/' + script)}"></script>` : ''}</head><body data-base="${base}" data-source="${sha}"><a class="skip" href="#main">Skip to content</a>
  <header class="site-header"><a class="wordmark" href="${href('')}" aria-label="zerocopy home">${logo}<span>zerocopy<span class="wordmark-dot">.</span></span></a><nav class="desktop-nav" aria-label="Main"><a href="${href('docs/getting-started/')}" ${route.startsWith('docs/') ? 'aria-current="page"' : ''}>Documentation</a><a href="${href('use-cases/')}" ${route === 'use-cases/' ? 'aria-current="page"' : ''}>Use cases</a><a href="${href('lab/')}" ${route === 'lab/' ? 'aria-current="page"' : ''}>Benchmark lab</a></nav><div class="header-actions"><button class="search-open" aria-label="Search documentation"><svg width="17" height="17" viewBox="0 0 20 20" aria-hidden="true"><circle cx="8" cy="8" r="5.5" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="m12 12 5 5" stroke="currentColor" stroke-width="1.5"/></svg><span>Search</span><kbd>⌘ K</kbd></button><a class="github-link" href="${repository}">GitHub ${arrow}</a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav">Menu</button></div></header>
  <nav id="mobile-nav" class="mobile-nav" aria-label="Mobile" hidden><a href="${href('docs/getting-started/')}">Documentation</a><a href="${href('use-cases/')}">Use cases</a><a href="${href('playground/')}">Snapshot playground</a><a href="${href('lab/')}">Benchmark lab</a><a href="${repository}">GitHub</a></nav>
  ${body}
  <footer class="site-footer"><div><a class="wordmark" href="${href('')}">${logo}<span>zerocopy.</span></a><p>Share your data. Keep your options.</p></div><div class="footer-links"><a href="${href('docs/getting-started/')}">Get started</a><a href="${href('docs/memory/')}">Know the trade-offs</a><a href="${repository}/issues">Feedback ${arrow}</a><a href="${repository}/blob/main/LICENSE">MIT license</a></div><p class="build-info">Source build v${escape(version)} · <a href="${repository}/commit/${sha}">${sha.slice(0, 7)}</a><br>No analytics. Benchmarks stay in your browser.</p></footer>
  <dialog class="search-dialog" aria-labelledby="search-title"><div class="search-top"><label id="search-title" for="search-input">Search the docs</label><button class="search-close" aria-label="Close search">Esc</button></div><input id="search-input" type="search" placeholder="Try “worker”, “typed object”, or “compaction”…" autocomplete="off"><p id="search-status" role="status">Type a topic to find a guide.</p><div id="search-results"></div></dialog><div class="toast" role="status" aria-live="polite"></div>
  </body></html>`;
}

export function home(base) {
  return `<main id="main"><section class="hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> OPEN SOURCE / TYPESCRIPT + WEBASSEMBLY</div><h1>Share your data.<br><span>Not copies.</span></h1><p class="hero-description">One dataset. Your UI and workers, reading together. Immutable collections that cross threads without cloning their backing storage.</p><div class="hero-buttons"><a class="button primary" href="${base}docs/getting-started/">Start building ${arrow}</a><a class="button secondary" href="${base}playground/">See it work <span aria-hidden="true">→</span></a></div><p class="hero-note">Direct reads. Familiar collections. Tasks optional.</p></div>
  <div class="sharing-card" aria-label="Interactive conceptual view of shared and cloned storage"><div class="diagram-toolbar"><span class="diagram-title">A DIFFERENT WAY TO SHARE</span><div class="segmented" role="group" aria-label="Storage model"><button data-storage="shared" aria-pressed="true">Shared</button><button data-storage="cloned" aria-pressed="false">Cloned</button></div></div><div class="diagram"><div class="owner-node"><span class="node-icon">UI</span><span>Main thread<small>Keep editing</small></span><span class="node-live">●</span></div><div class="wire wire-top"></div><div class="arena"><div class="arena-header"><span>YOUR DATASET</span><span id="arena-label">Shared backing storage</span></div><div class="memory-grid" aria-hidden="true">${Array.from({ length: 32 }, (_, i) => `<i style="--i:${i}"></i>`).join('')}</div><div class="arena-footer"><span class="mono">Map · List · Set</span><span>Immutable snapshots</span></div></div><div class="wire wire-bottom"></div><div class="reader-nodes" id="reader-nodes"></div></div><div class="diagram-controls"><label for="worker-count">Workers <output id="worker-count-value">3</output></label><input id="worker-count" type="range" min="1" max="4" value="3"><span id="storage-count" role="status">1 backing store</span></div><p class="diagram-caption">Conceptual storage model. Not a memory measurement.</p></div></section>
  <section class="promise-strip wrap" aria-label="Core benefits"><div><span class="small-index">01</span><strong>Shared storage</strong><span>Not a full dataset per worker.</span></div><div><span class="small-index">02</span><strong>Local reads</strong><span>No round trip for every value.</span></div><div><span class="small-index">03</span><strong>Immutable versions</strong><span>New edits. Stable earlier snapshots.</span></div></section>
  <section class="section wrap split-section" id="how-it-works"><div><div class="eyebrow">THE GOOD PART</div><h2>Move the work.<br>Not the whole dataset.</h2><p class="section-lead">Check product stock with a familiar .get()—on either thread.</p><p>Connect a worker once. A session delivers snapshots. After attachment, <code>.get()</code> is a synchronous local read. It does not ask the main thread for a value.</p><a class="text-link" href="${base}docs/mental-model/">Understand the model <span>→</span></a><div class="inline-note">Collections hold data. Sessions share snapshots.<br><strong>Tasks only schedule work.</strong></div></div><div class="code-demo"><div class="code-tabs" role="tablist" aria-label="Thread example"><button role="tab" aria-selected="true" id="tab-owner" aria-controls="panel-owner" data-code-tab="owner">main.ts</button><button role="tab" aria-selected="false" id="tab-reader" aria-controls="panel-reader" tabindex="-1" data-code-tab="reader">worker.ts</button></div><div role="tabpanel" id="panel-owner" aria-labelledby="tab-owner">${codeBlock(`// With your existing state and worker\nawait state.connect(worker);\n\n// Read directly on the main thread.\nstate.current.stock.get('headphones');\n\n// Inventory update: headphones are sold out.\nstate.update('stock', stock =>\n  stock.set('headphones', 0)\n);`, 'Main thread · API excerpt')}</div><div role="tabpanel" id="panel-reader" aria-labelledby="tab-reader" hidden>${codeBlock(`import { connectSharedSession }\n  from 'zerocopy/worker';\n\nconst shared = await connectSharedSession<Model>();\n\n// No task. No per-read message.\nconst snapshot = shared.current;\nconst quantity = snapshot.stock.get('headphones');\n\n// This snapshot stays fixed across later updates.`, 'Worker · API excerpt')}</div><div class="code-demo-bottom"><span class="status-dot"></span> Local read. Not RPC.<a href="${base}docs/getting-started/">Complete setup →</a></div></div></section>
  <section class="snapshot-promo"><div class="wrap snapshot-promo-inner"><div><div class="eyebrow">TRY IT, DON'T TAKE OUR WORD FOR IT</div><h2>Make an edit.<br>Keep the old version.</h2><p>Mark a product as sold out. Watch the current stock change while a worker keeps its earlier, in-stock snapshot.</p><a class="button primary" href="${base}playground/">Open the playground ${arrow}</a></div><div class="snapshot-preview" aria-label="Headphones: an in-stock snapshot and a sold-out snapshot"><div class="snapshot-card"><span class="mono">SNAPSHOT 01 / RETAINED</span><div class="stock-value">12<span>units</span></div><code>before.get('headphones')</code><span class="snapshot-status">12 units. In stock.</span></div><div class="snapshot-arrow" aria-hidden="true">→</div><div class="snapshot-card next"><span class="mono">SNAPSHOT 02 / NEW</span><div class="stock-value">0<span>units</span></div><code>after.get('headphones')</code><span class="snapshot-status">0 units. Sold out.</span></div></div></div></section>
  <section class="section wrap"><div class="section-heading"><div><div class="eyebrow">BUILT FOR SHARED WORK</div><h2>Big data. Busy interfaces.</h2></div><a class="text-link" href="${base}use-cases/">Explore the patterns →</a></div>${useCaseCards(base)}</section>
  <section class="lab-promo wrap"><div><div class="eyebrow">YOUR BROWSER. YOUR RESULTS.</div><h2>Don't benchmark<br>the marketing.</h2><p>Compare shared snapshots with a structured-cloned native Map. Choose the dataset and worker count. Run the actual code, check the output, and keep the raw samples.</p><a class="button primary" href="${base}lab/">Run a live benchmark ${arrow}</a><p class="lab-small">No prefilled winner. No result sent to a server.</p></div><div class="lab-preview"><div class="code-label"><span>BENCHMARK LAB</span><span>Ready when you are</span></div><div class="preview-metric"><span>Shared snapshot</span><div class="empty-bar"></div><strong>— ms</strong></div><div class="preview-metric"><span>Structured-cloned Map</span><div class="empty-bar"></div><strong>— ms</strong></div><div class="lab-preview-foot"><span>Same inputs</span><span>Rotated order</span><span>Checked results</span></div><p>Real timings appear only after you run it.</p></div></section>
  <section class="section wrap fit-section"><div><div class="eyebrow">THE RIGHT TOOL, NOT EVERY TOOL</div><h2>Keep your stack.<br>Know the trade-offs.</h2><p>Start with a collection. Bring your existing workers, Redux store, or message protocol. Add a task pool when you need one.</p><a class="text-link" href="${base}docs/getting-started/">Find your starting point →</a></div><div class="fit-details"><details open><summary>Where zerocopy fits</summary><p>Large, versioned collections that multiple threads need to read. Product catalogs, editors, maps, and analysis tools with a changing dataset.</p></details><details><summary>What you need to know</summary><p>Browsers need cross-origin isolation. Each arena has one allocating writer. Worker snapshots arrive asynchronously. Long-lived data needs an explicit compaction strategy.</p><a href="${base}docs/memory/">Read the memory guide →</a></details><details><summary>When native collections are better</summary><p>Small data that stays on one thread. Sharing avoids dataset copies; it does not make every collection operation faster or remove all allocations.</p><a href="${base}docs/benchmarks/">See the full recorded results →</a></details></div></section>
  <section class="closing wrap"><span class="eyebrow">LESS COPYING. MORE BUILDING.</span><h2>Your next worker<br>can read the same data.</h2><a class="button primary" href="${base}docs/getting-started/">Connect your first worker ${arrow}</a><a class="text-link" href="${repository}">Explore the source ↗</a></section></main>`;
}

export function useCaseCards(base) {
  const cards = [
    ['analytics', '01 / PRODUCT CATALOGS', 'Keep your catalog current.', 'Read stock in the UI. Filter available products in a worker. Keep the same shared dataset.', '<rect x="15" y="15" width="46" height="70" rx="5"/><rect x="77" y="15" width="46" height="70" rx="5"/><rect x="139" y="15" width="46" height="70" rx="5"/><path d="M25 64h26M87 64h26M149 64h26M25 74h15M87 74h15M149 74h15"/><circle cx="38" cy="38" r="12"/><circle cx="100" cy="38" r="12"/><circle cx="162" cy="38" r="12"/>'],
    ['editors', '02 / CREATIVE TOOLS', 'Edit without stopping.', 'Keep stable versions for background checks. Apply results only when they are still relevant.', '<rect x="20" y="10" width="100" height="80" rx="5"/><path d="M40 30h55M40 44h30M40 58h60M40 72h40"/><rect x="110" y="38" width="70" height="54" rx="4"/>'],
    ['maps', '03 / SPATIAL', 'Keep the map moving.', 'Inspect routes and lane data in workers while the owner accepts new edits.', '<path d="M0 90 65 30 110 65 190 0M0 5 75 80 140 60 200 95M35 0 55 50 0 100M135 0 95 100"/><circle cx="110" cy="65" r="7"/><circle cx="55" cy="50" r="5"/>'],
  ];
  return `<div class="use-case-grid">${cards.map(([slug, label, title, text, art]) => `<a class="use-case-card" href="${base}docs/${slug}/"><div class="case-art ${slug}"><svg viewBox="0 0 200 100" aria-hidden="true">${art}</svg><span class="case-arrow">↗</span></div><div class="case-copy"><span class="eyebrow">${label}</span><h3>${title}</h3><p>${text}</p><span class="text-link">Read the pattern →</span></div></a>`).join('')}</div>`;
}

export function docsLayout(page, html, toc, pages, base, sha) {
  const groups = [...new Set(pages.map(p => p.group))];
  return `<div class="docs-layout"><aside class="docs-sidebar" aria-label="Documentation"><p class="eyebrow">DOCUMENTATION</p>${groups.map(group => `<div class="sidebar-group"><h2>${group}</h2>${pages.filter(p => p.group === group).map(p => `<a href="${base}docs/${p.slug}/" ${p.slug === page.slug ? 'aria-current="page"' : ''}>${escape(p.title)}</a>`).join('')}</div>`).join('')}<a class="sidebar-lab" href="${base}lab/">↗ Benchmark lab</a></aside><main class="doc-main" id="main"><details class="mobile-docs-menu"><summary>Browse documentation</summary><nav aria-label="All documentation">${pages.map(p => `<a href="${base}docs/${p.slug}/">${escape(p.title)}</a>`).join('')}</nav></details><div class="doc-breadcrumb">${escape(page.group)} <span>/</span> ${escape(page.title)}</div><h1>${escape(page.title)}</h1><p class="doc-description">${escape(page.description)}</p><div class="doc-meta"><span>Source documentation</span><a href="${repository}/blob/${sha}/${page.source}">View source ↗</a><button class="copy-page" data-markdown="${base}markdown/${page.slug}.md">Copy Markdown</button></div><article class="prose">${html}</article><div class="doc-bottom"><span>Found something unclear?</span><a href="${repository}/issues/new">Improve this guide ↗</a></div></main><aside class="doc-toc" aria-label="On this page"><p class="eyebrow">ON THIS PAGE</p>${toc.filter(item => item.depth === 2).map(item => `<a href="#${escape(item.id)}">${escape(item.text)}</a>`).join('')}<a class="toc-help" href="${base}playground/">Try a real snapshot →</a></aside></div>`;
}

export function isolationNotice() {
  return `<div class="capability-notice" id="capability" role="status"><span class="status-dot"></span><span id="capability-text">Checking shared-memory support…</span><button id="enable-isolation" hidden>Enable shared memory & reload</button></div><p class="capability-help" id="capability-help" hidden>On hosts without isolation headers, this installs a same-origin service worker for this demo path, then reloads once. It does not cache requests. The rest of the docs work without it.</p>`;
}

export function lab(base) {
  return `<main id="main" class="lab-page wrap"><div class="page-intro"><div class="eyebrow">THE BENCHMARK LAB</div><h1>Evidence.<br><span>Not promises.</span></h1><p>Run zerocopy against structured-cloned native data. In your browser. On your hardware. With every result checked.</p></div>${isolationNotice()}<div class="lab-workspace"><form id="benchmark-form" class="lab-controls"><div class="panel-heading"><span class="small-index">01</span><h2>Set your workload</h2></div><label for="entries">Dataset size</label><select id="entries"><option value="1000">1,000 entries</option><option value="10000" selected>10,000 entries</option><option value="50000">50,000 entries</option></select><label for="readers">Dedicated workers</label><select id="readers"><option value="1">1 worker</option><option value="2" selected>2 workers</option><option value="4">4 workers</option></select><div class="workload-spec"><span>Shape</span><strong>String keys → numbers</strong><span>Samples</span><strong>7 per path + 2 warm-ups</strong><span>Operation</span><strong>Publish, attach, read all</strong></div><button class="button primary" id="run-benchmark" disabled>Run benchmark <span aria-hidden="true">→</span></button><button class="button secondary" id="cancel-benchmark" type="button" hidden>Stop run</button><p class="muted">This uses CPU and memory. Run it in a foreground tab. All data is generated locally.</p></form><section class="lab-results" aria-labelledby="results-heading"><div class="panel-heading"><span class="small-index">02</span><h2 id="results-heading">Read the results</h2><span class="live-label">LIVE / LOCAL</span></div><div id="benchmark-status" role="status" aria-live="polite">Ready for a real result.</div><progress id="benchmark-progress" max="18" value="0" aria-label="Benchmark progress" hidden></progress><div class="result-chart" id="benchmark-chart"><div class="result-row"><div><span>zerocopy</span><strong>— <small>ms</small></strong></div><div class="result-track"></div></div><div class="result-row"><div><span>Structured-cloned Map</span><strong>— <small>ms</small></strong></div><div class="result-track"></div></div><p class="empty-result">No stored scores. Press Run to measure.</p></div><div id="benchmark-summary" class="result-summary" hidden></div><div id="benchmark-detail"></div><div class="result-actions"><button id="export-results" class="button secondary" disabled>Download raw JSON ↓</button><a href="#method">Read the method →</a></div></section></div>
  <section class="section method-section" id="method"><div><div class="eyebrow">THE SMALL PRINT IS THE POINT</div><h2>What this actually measures.</h2><p class="section-lead">End-to-end fan-out and reads. Not a pure transfer benchmark. Not a memory benchmark.</p></div><div class="method-grid"><div><h3>Included</h3><p>Snapshot descriptor creation, sending to all readers, structured cloning or shared attachment, a lookup for every key, and the response. Shared attachment creates new read-only views on each trial.</p></div><div><h3>Excluded</h3><p>Worker startup and library loading happen before warm-up. Dataset construction happens once, with its own reported timing. It is not included in the comparison bars.</p></div><div><h3>Same job. Checked answers.</h3><p>Both paths use the same deterministic string keys and numeric values. Each reader reports a checksum. A mismatch fails the run. Measurement order alternates, and the median and interquartile range use all seven samples.</p></div><div><h3>No universal winner</h3><p>Native Map can win, especially for small data. Warm-up does not remove per-publication attachment costs. This test does not measure persistent edit history, every value type, or your application's workload.</p></div></div><div class="method-links"><a href="${base}docs/benchmarks/">All recorded collection benchmarks →</a><a href="${repository}/blob/main/website/assets/bench-runner.mjs">Inspect the benchmark source ↗</a></div></section></main>`;
}

export function playground(base) {
  return `<main id="main" class="wrap playground-page"><div class="page-intro"><div class="eyebrow">A REAL SHARED-MEMORY PLAYGROUND</div><h1>New edits.<br><span>Unchanged history.</span></h1><p>Start a real dedicated worker. Headphones start with 12 units in stock. Mark them as sold out, then compare the live catalog with the worker's retained snapshot.</p></div>${isolationNotice()}<div class="playground-controls"><button class="button primary" id="start-playground" disabled>Connect a worker →</button><label for="stock">Headphones in stock <input id="stock" type="number" min="0" max="200" step="1" value="0" disabled><span>units</span></label><button class="button secondary" id="apply-edit" disabled>Apply edit ↗</button><button class="text-button" id="stop-playground" disabled>Disconnect</button></div><div class="snapshot-live-grid"><div class="snapshot-live owner"><span class="eyebrow">MAIN THREAD / OWNER</span><h2>Current state</h2><div class="stock-value" id="owner-value">—<span>units</span></div><p class="stock-status" id="owner-availability" aria-live="polite">Not loaded</p><code>state.current.stock.get('headphones')</code><p>Updates synchronously.</p></div><div class="snapshot-live reader"><span class="eyebrow">WORKER / RECEIVED</span><h2>Latest snapshot</h2><div class="stock-value" id="reader-value">—<span>units</span></div><p class="stock-status" id="reader-availability" aria-live="polite">Not loaded</p><code>shared.current.stock.get('headphones')</code><p>Receives new roots asynchronously.</p></div><div class="snapshot-live retained"><span class="eyebrow">WORKER / RETAINED</span><h2>First snapshot</h2><div class="stock-value" id="retained-value">—<span>units</span></div><p class="stock-status" id="retained-availability" aria-live="polite">Not loaded</p><code>initial.stock.get('headphones')</code><p>Stays unchanged after later edits.</p></div></div><div class="playground-bottom"><div class="event-log"><div class="code-label"><span>LIVE EVENT LOG</span><span>Actual worker messages</span></div><ol id="snapshot-log" role="log" aria-live="polite"><li>Ready. No worker is running yet.</li></ol></div><div class="playground-explainer"><h2>What to notice</h2><p>The owner changes first. The worker sees the new value after a snapshot arrives. Its first snapshot still shows <strong>12 units in stock</strong>, even when the current value is zero.</p><p>Each collection read happens locally, outside any task. The worker sends small reports only so this page can display the results.</p><a class="text-link" href="${base}docs/getting-started/">Build this into your app →</a></div></div><p class="lab-small">This uses the real source build shipped with this site. Disconnect releases the session and terminates this worker. Browser page navigation also ends the demo. This is a local catalog view, not stock reservation; checkout still needs server validation.</p></main>`;
}
